name: 'Dependency Check'
description: 'Github action to execute dependency check as part of a github workflow'
Author: 'javixeneize'
branding:
  icon: 'shield'  
  color: 'red'
inputs:
    project:
        required: true
    path:
        required: true  
    format1:
        required: true
    format2:
        required: false
    out:
        required: true
        default: 'reports'
    failoncvss:
        required: false
    others:
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:

        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format1 }}'
        - '--format' 
        - '${{ inputs.format2 }}'
        - '--failOnCVSS' 
        - '${{ inputs.failoncvss }}'
        - '--out'
        -  '/github/workspace/${{ inputs.out }}'
        - '--noupdate'
        - ${{ inputs.args }}
