name: 'Parameterized Dependency Check'
description: 'Github action to execute dependency check as part of a github workflow'
Author: 'javixeneize, forked by MorsiC'
branding:
  icon: 'shield'  
  color: 'red'
inputs:
    project:
       required: true
    path:
       required: true  
    format1:
       required: true
       default: 'HTML'
    format2:
       required: false
    out:
       required: true
       default: 'reports'
    failOnCVSS:
       required: true
       default: 7
    junitFailOnCVSS:
       required: true
       default: 7
    exclude:
        required: true
    disableRetireJS:
        description: 'Optionnally, enable JS analysis. Keep empty to keep JS analysis disabled'
        required: false
    others:
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format1 }}'
        - '--format' 
        - ${{ [inputs.format1, inputs.format2][inputs.format2] }}
        - '--failOnCVSS' 
        - '${{ inputs.failOnCVSS }}'
        - '--junitFailOnCVSS' 
        - '${{ inputs.junitFailOnCVSS }}'
        - '--out'
        -  '/github/workspace/${{ inputs.out }}'
        - '--exclude'
        -  '${{ inputs.exclude }}'
        - '--noupdate'
        - ${{ ["--disableRetireJS", "--noupdate"][inputs.disableRetireJS] }}
        - ${{ inputs.others }}
